
apiVersion: v1
kind: Service
metadata:
  name: ckb
  namespace: default
  labels:
    app: ckb
spec:
  selector:
    app: ckb
  ports:
    - protocol: TCP
      name: ckb-rpc
      port: 8114
      targetPort: 8114
    - protocol: TCP
      name: ckb-p2p
      port: 8115
      targetPort: 8115