
apiVersion: v1
kind: Service
metadata:
  name: rtl
  namespace: default
  labels:
    app: rtl
spec:
  selector:
    app: rtl
  ports:
    - protocol: TCP
      name: rtl-web
      port: 3000
      targetPort: 3000
