apiVersion: v1
kind: Service
metadata:
  name: ckb-nodeport
  namespace: default
  labels:
    app: ckb
spec:
  selector:
    app: ckb
  ports:
    - protocol: TCP
      name: ckb-rpc
      port: 8114
      targetPort: 8114
      nodePort: 30004
  type: NodePort