apiVersion: v1
kind: Service
metadata:
  name: bitcoin-nodeport
  namespace: default
  labels:
    app: bitcoin
spec:
  selector:
    app: bitcoin
  ports:
    - protocol: TCP
      name: bitcoin-rpc
      port: 8332
      targetPort: 8332
      nodePort: 30001
  type: NodePort
