apiVersion: v1
kind: Service
metadata:
  name: lnd-nodeport
  namespace: testnet
  labels:
    app: lnd
spec:
  selector:
    app: lnd
  ports:
    - protocol: TCP
      name: lnd-rest
      port: 8080
      targetPort: 8080
      nodePort: 30008
  type: NodePort