
apiVersion: v1
kind: Service
metadata:
  name: lnd
  namespace: testnet
  labels:
    app: lnd
spec:
  selector:
    app: lnd
  ports:
    - protocol: TCP
      name: lnd-rpc
      port: 10009
      targetPort: 10009
    - protocol: TCP
      name: lnd-rest
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: lnd-p2p
      port: 9735
      targetPort: 9735
