apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: agent
    app.kubernetes.io/name: bescard-agent
  name: bescard-agent
  namespace: default
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
      nodePort: 30012
  selector:
    app.kubernetes.io/instance: agent
    app.kubernetes.io/name: bescard-agent
  type: NodePort
