apiVersion: v1
kind: ConfigMap
data:
  torrc: |+
    # Ports
    SocksPort   127.0.0.1:9050
    ControlPort 127.0.0.1:9051

    # tor --hash-password passwordtogenerate
    HashedControlPassword 16:F6037168CB4D199660646ED37463953A4F77220A6FAEC180D09956CD8F

    # proxy
    Socks5Proxy 192.168.12.84:7897
metadata:
  labels:
    app: lnd-tor
  name: lnd-torrc