apiVersion: v1
kind: Pod
metadata:
  name: subnet-router
  namespace: default
  labels:
    app: tailscale
spec:
  serviceAccountName: tailscale
  containers:
    - name: tailscale
      image: tailscale/tailscale:v1.72.1
      env:
        - name: TS_KUBE_SECRET
          value: tailscale-auth
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
        - name: TS_ROUTES
          value: "10.42.0.0/16,10.43.0.0/16"
        - name: TS_USERSPACE
          value: "true"
      securityContext:
        # Run as a non-root user to mitigate privilege escalation attack attempts
        runAsUser: 1000
        runAsGroup: 1000