apiVersion: v1
kind: Service
metadata:
  name: bitcoin-lb
  namespace: default
  labels:
    app: bitcoin
spec:
  loadBalancerClass: tailscale # add this!
  type: LoadBalancer
  ports:
  - port: 8332
  selector:
    app: bitcoin