apiVersion: v1
kind: Service
metadata:
  name: bitcoin-lb
  namespace: regtest
  labels:
    app: bitcoin
spec:
  loadBalancerClass: tailscale # add this!
  type: LoadBalancer
  ports:
  - port: 18443
  selector:
    app: bitcoin