apiVersion: v1
kind: Service
metadata:
  name: ckb-lb
  namespace: default
  labels:
    app: ckb
spec:
  loadBalancerClass: tailscale # add this!
  type: LoadBalancer
  ports:
  - port: 8114
  selector:
    app: ckb