apiVersion: v1
kind: Service
metadata:
  name: lnd-lb
  namespace: default
  labels:
    app: lnd
spec:
  loadBalancerClass: tailscale # add this!
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: lnd