apiVersion: v1
kind: Service
metadata:
  name: rtl-lb
  namespace: testnet
  labels:
    app: rtl
spec:
  loadBalancerClass: tailscale # add this!
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: rtl