
apiVersion: v1
kind: Service
metadata:
  name: bitcoin
  namespace: regtest
  labels:
    app: bitcoin
spec:
  selector:
    app: bitcoin
  ports:
    - protocol: TCP
      name: bitcoin-rpc
      port: 18443
      targetPort: 18443
    - protocol: TCP
      name: zmp-block
      port: 28332
      targetPort: 28332
    - protocol: TCP
      name: zmp-tx
      port: 28333
      targetPort: 28333